FROM node:20.19-alpine

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY entrypoint.sh /usr/local/bin/
RUN chmod +x /usr/local/bin/entrypoint.sh

COPY . .

EXPOSE 8080

ENTRYPOINT ["entrypoint.sh"]
CMD ["npm", "run", "dev"]