services:
  frontend:
    container_name: usv-hmi-frontend
    build:
      context: ../../frontend
    ports:
      - "8080:8080"
    volumes:
      - ../../frontend:/app
      - /app/node_modules
    command: npm run dev
  backend:
    container_name: usv-hmi-backend
    build:
      context: ../../backend
    ports:
      - "8000:8000"